server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/estate

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

